(() => {
'use strict';
const SUPABASE_URL='https://jmnnesumjpkraugtzdkl.supabase.co';
const SUPABASE_KEY='sb_publishable__CO_CJqvrVqG-LClfcD_Wg_CVdZZZU8';
const CATALOG=(window.LG_CATALOG||[]).map((p,i)=>({...p,order:i}));
const icons={'Aircond':'❄️','Laundry':'🧺','Fridge':'🧊','Air Purifier':'🌿','Water Purifier':'💧','TV':'📺'};
let activeCat='All',cart=[],activeProduct=null,chosenPlan=null,chosenPromo='standard',stocks=new Map(),stockLoaded=false;
const $=id=>document.getElementById(id);
const money=n=>'RM'+Math.max(0,Math.round(Number(n)||0)).toLocaleString('en-MY');
const baseCode=s=>String(s||'').split('.')[0].toUpperCase().replace(/\s+/g,'');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const minPrice=p=>Math.min(...p.plans.map(x=>Number(x.monthly)||999999));
const stockFor=p=>stocks.get(baseCode(p.code))||null;
const icon=p=>icons[p.category]||'LG';
function stockBadge(p){const s=stockFor(p);if(!s)return stockLoaded?'<span class="stock-badge loading">Stock not listed</span>':'<span class="stock-badge loading">Stock: syncing…</span>';const n=Math.max(0,Math.round(Number(s.total_stock)||0));const c=n<=0?'out':n<=3?'low':'good';return '<span class="stock-badge '+c+'">'+(n<=0?'Out of stock':n<=3?'Low stock: '+n:'Stock: '+n)+'</span>';}
function visual(p){return p.imageData?'<img src="'+p.imageData+'" alt="'+esc(p.name)+'">':'<div class="generic-icon">'+icon(p)+'</div>';}
function renderCats(){const cats=['All',...new Set(CATALOG.map(x=>x.category))];$('catRow').innerHTML=cats.map(c=>'<button class="cat '+(c===activeCat?'active':'')+'" data-cat="'+esc(c)+'">'+esc(c)+'</button>').join('');$('catRow').querySelectorAll('.cat').forEach(b=>b.onclick=()=>{activeCat=b.dataset.cat;renderCats();renderProducts();});}
function visibleProducts(){const q=($('search')?.value||'').trim().toLowerCase(),sort=$('sort')?.value||'featured';let rows=CATALOG.filter(p=>(activeCat==='All'||p.category===activeCat)&&(!q||((p.code+' '+p.name+' '+p.category).toLowerCase().includes(q))));if(sort==='price')rows.sort((a,b)=>minPrice(a)-minPrice(b));else if(sort==='model')rows.sort((a,b)=>a.code.localeCompare(b.code));else rows.sort((a,b)=>a.order-b.order);return rows;}
function renderProducts(){const rows=visibleProducts();$('catalogCount').textContent=rows.length+' model';$('products').innerHTML=rows.map(p=>{const s=stockFor(p),n=s?Math.max(0,Math.round(Number(s.total_stock)||0)):null,disabled=n===0;return '<article class="product '+(disabled?'unavailable':'')+'"><div class="pvisual">'+stockBadge(p)+visual(p)+'</div><div class="pbody"><div class="pcat">'+esc(p.category)+'</div><h3>'+esc(p.code)+'</h3><div class="psub">'+esc(p.name)+'</div><span class="lifecycle current">Current selection</span><div class="price"><div><small>From</small><strong>'+money(minPrice(p))+'</strong><em>/month</em></div></div><button class="addbtn" data-id="'+p.id+'" '+(disabled?'disabled':'')+'>'+(disabled?'Out of stock':'View plans')+'</button></div></article>';}).join('');$('products').querySelectorAll('.addbtn:not(:disabled)').forEach(b=>b.onclick=()=>openProduct(b.dataset.id));}
function openProduct(id){activeProduct=CATALOG.find(x=>x.id===id);if(!activeProduct)return;chosenPlan=activeProduct.plans[0];chosenPromo='standard';$('qtyInput').value=1;$('modalModel').textContent=activeProduct.code;$('modalSub').textContent=activeProduct.name;const s=stockFor(activeProduct);$('modalStock').innerHTML=s?'Live stock: <b>'+Math.round(Number(s.total_stock)||0)+'</b> unit · AL2 '+Math.round(Number(s.al2_stock)||0)+' · AL3 '+Math.round(Number(s.al3_stock)||0)+' · AL8 '+Math.round(Number(s.al8_stock)||0)+(s.as_of_date?' · As of '+s.as_of_date:''):'Stock data syncing…';renderPlans();renderPromos();$('modal').showModal();}
window.closeModal=()=>$('modal').close();
window.stepQty=d=>{const q=$('qtyInput');q.value=Math.max(1,Math.min(9,(Number(q.value)||1)+d));};
function renderPlans(){$('planGrid').innerHTML=activeProduct.plans.map((p,i)=>'<button class="plan-card '+(p===chosenPlan?'active':'')+'" data-i="'+i+'"><b>'+p.years+' years</b><span>'+esc(p.service)+'</span><strong>'+money(p.monthly)+'/month</strong></button>').join('');$('planGrid').querySelectorAll('.plan-card').forEach(b=>b.onclick=()=>{chosenPlan=activeProduct.plans[Number(b.dataset.i)];renderPlans();});}
function renderPromos(){$('promoGrid').innerHTML=activeProduct.promos.map(p=>'<button class="promo-card '+(p.id===chosenPromo?'active':'')+'" data-id="'+p.id+'"><b>'+esc(p.label)+'</b><span>'+(p.id==='half9'?'Subject to current campaign eligibility':p.id==='combo10'?'Applies when package has 2+ units':'No introductory discount')+'</span></button>').join('');$('promoGrid').querySelectorAll('.promo-card').forEach(b=>b.onclick=()=>{chosenPromo=b.dataset.id;renderPromos();});}
function monthlyFor(item,month,unitCount){let m=Number(item.plan.monthly)||0;if(item.promo==='half9'&&month<=9)m*=.5;if(item.promo==='combo10'&&unitCount>=2)m=Math.max(0,m-10);return m*item.qty;}
function addActive(){if(!activeProduct||!chosenPlan)return;const qty=Math.max(1,Math.min(9,Number($('qtyInput').value)||1));cart.push({key:Date.now()+Math.random(),product:activeProduct,plan:{...chosenPlan},promo:chosenPromo,qty});closeModal();renderCart();toast('Added to package');}
function totalUnits(){return cart.reduce((a,x)=>a+x.qty,0);}
function renderCart(){const units=totalUnits();$('cartUnits').textContent=units+' unit';$('selectedCount').textContent=units+' product selected';if(!cart.length){$('cartItems').innerHTML='<div class="room-empty" style="padding:16px">No products yet.</div>';$('roomGrid').innerHTML='<div class="room-empty"><b>Start with one appliance</b><br>Select a product below to build a package for your home.</div>';$('currentMonthly').textContent='RM0';$('scheduleRows').innerHTML='';$('saving').textContent='RM0';$('contractTotal').textContent='RM0';budgetCheck();syncUrl(false);return;}$('cartItems').innerHTML=cart.map((x,i)=>'<div class="cart-item"><div><b>'+esc(x.product.code)+'</b><span>'+x.qty+' × '+x.plan.years+'Y · '+esc(x.plan.service)+'</span><small>'+esc((x.product.promos.find(p=>p.id===x.promo)||{}).label||'')+'</small></div><button data-i="'+i+'" class="remove">×</button></div>').join('');$('cartItems').querySelectorAll('.remove').forEach(b=>b.onclick=()=>{cart.splice(Number(b.dataset.i),1);renderCart();});$('roomGrid').innerHTML=cart.map(x=>'<div class="room-item"><div class="qtydot">×'+x.qty+'</div><div class="miniimg">'+visual(x.product)+'</div><b>'+esc(x.product.code)+'</b><span>'+esc(x.product.name)+'</span></div>').join('');$('currentMonthly').textContent=money(cart.reduce((a,x)=>a+monthlyFor(x,1,units),0));renderSchedule();budgetCheck();syncUrl(false);}
function renderSchedule(){const units=totalUnits(),maxMonths=Math.max(...cart.map(x=>x.plan.years*12)),cuts=new Set([1,maxMonths+1]);cart.forEach(x=>{if(x.promo==='half9')cuts.add(10);cuts.add(x.plan.years*12+1);});const pts=[...cuts].filter(n=>n>=1&&n<=maxMonths+1).sort((a,b)=>a-b);let rows=[],total=0,standard=0;for(let i=0;i<pts.length-1;i++){const a=pts[i],b=pts[i+1]-1;if(a>b)continue;const m=cart.reduce((s,x)=>a<=x.plan.years*12?s+monthlyFor(x,a,units):s,0),normal=cart.reduce((s,x)=>a<=x.plan.years*12?s+(Number(x.plan.monthly)||0)*x.qty:s,0),months=b-a+1;total+=m*months;standard+=normal*months;rows.push('<div class="schedule-row"><span>Month '+a+(b>a?'–'+b:'')+'</span><b>'+money(m)+'/month</b></div>');}$('scheduleRows').innerHTML=rows.join('');$('saving').textContent=money(Math.max(0,standard-total));$('contractTotal').textContent=money(total);}
function budgetCheck(){const budget=Number($('budget')?.value)||0,cur=Number($('currentMonthly')?.textContent.replace(/[^\d.]/g,''))||0,e=$('budgetResult');if(!cart.length){e.textContent='Build your package to compare with budget.';e.className='budget-result';return;}if(cur<=budget){e.textContent='Within budget by '+money(budget-cur)+'/month';e.className='budget-result ok';}else{e.textContent='Over budget by '+money(cur-budget)+'/month';e.className='budget-result over';}}
async function loadStock(){try{const r=await fetch(SUPABASE_URL+'/rest/v1/rpc/get_public_stock',{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY,'Content-Type':'application/json'},body:'{}'});if(!r.ok)throw new Error('HTTP '+r.status);const rows=await r.json();stocks=new Map(rows.map(x=>[baseCode(x.model_code),x]));stockLoaded=true;const dates=rows.map(x=>x.as_of_date).filter(Boolean).sort(),d=dates.at(-1)||'latest';$('liveDot').className='live-dot ok';$('liveText').textContent='Live stock connected';$('stockStamp').textContent='Stock synced · '+d;$('stockInfo').textContent='Stock quantity is read live from the same Supabase stock table used by the LG Subscribe Control Centre. Refresh this page after a stock upload to see the latest balance.';renderProducts();}catch(e){console.warn(e);stockLoaded=true;$('liveDot').className='live-dot err';$('liveText').textContent='Stock temporarily unavailable';$('stockStamp').textContent='Stock sync unavailable';renderProducts();}}
function payload(){return cart.map(x=>({id:x.product.id,plan:x.product.plans.findIndex(p=>p.years===x.plan.years&&p.service===x.plan.service&&p.monthly===x.plan.monthly),promo:x.promo,qty:x.qty}));}
function syncUrl(push=true){const u=new URL(location.href);if(cart.length)u.searchParams.set('pkg',btoa(unescape(encodeURIComponent(JSON.stringify(payload())))).replace(/=+$/,''));else u.searchParams.delete('pkg');if(push)history.pushState({},'',u);else history.replaceState({},'',u);}
function loadFromUrl(){const v=new URL(location.href).searchParams.get('pkg');if(!v)return;try{const pad=v+'==='.slice((v.length+3)%4),data=JSON.parse(decodeURIComponent(escape(atob(pad))));cart=data.map(x=>{const p=CATALOG.find(y=>y.id===x.id);if(!p)return null;const plan=p.plans[x.plan]||p.plans[0];return{key:Date.now()+Math.random(),product:p,plan:{...plan},promo:p.promos.some(z=>z.id===x.promo)?x.promo:'standard',qty:Math.max(1,Math.min(9,Number(x.qty)||1))};}).filter(Boolean);}catch(e){console.warn('bad package link',e);}}
function sharePackage(){syncUrl(false);navigator.clipboard?.writeText(location.href).then(()=>toast('Package link copied')).catch(()=>prompt('Copy this link',location.href));}
function wa(){const lines=['Hi Jason, saya berminat dengan pakej LG Subscribe ini:'];cart.forEach(x=>lines.push('• '+x.qty+'x '+x.product.code+' — '+x.plan.years+'Y '+x.plan.service+' — '+((x.product.promos.find(p=>p.id===x.promo)||{}).label||'')));lines.push('Anggaran sekarang: '+$('currentMonthly').textContent+'/bulan',location.href);window.open('https://wa.me/601159726619?text='+encodeURIComponent(lines.join('\n')),'_blank');}
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800);}
window.scrollToCatalog=()=>$('catalogSection').scrollIntoView({behavior:'smooth',block:'start'});
window.scrollToPackage=()=>$('packageSide').scrollIntoView({behavior:'smooth',block:'start'});
document.addEventListener('DOMContentLoaded',()=>{renderCats();loadFromUrl();renderProducts();renderCart();loadStock();$('search').addEventListener('input',renderProducts);$('sort').addEventListener('change',renderProducts);$('budget').addEventListener('input',budgetCheck);$('modalAdd').onclick=addActive;$('shareBtn').onclick=sharePackage;$('waBtn').onclick=wa;$('resetBtn').onclick=()=>{cart=[];renderCart();toast('Package cleared');};$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal();});});
})();